# Generated by Django 5.0.8 on 2024-09-03 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_country_payment_email_payment_first_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
