# Generated by Django 5.0.13 on 2025-03-25 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(default='null')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('DRESS', 'Dress'), ('BAGS', 'Bags'), ('T-Shirts', 'T-Shirts'), ('SHIRTS', 'Shirts'), ('SKIRTS', 'Skirts')], default='DRESS', max_length=50)),
                ('image', models.ImageField(upload_to='product_images/')),
                ('alternate_image', models.ImageField(upload_to='product_images/')),
                ('collection', models.CharField(choices=[('COLLECTION_A', 'Collection A'), ('COLLECTION_B', 'Collection B'), ('COLLECTION_C', 'Collection C')], default='COLLECTION_A', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(blank=True, default='nill', max_length=255)),
                ('last_name', models.TextField(blank=True, default='nill', max_length=255)),
                ('email', models.EmailField(default='nill', max_length=254)),
                ('street', models.CharField(blank=True, default='nill', max_length=255)),
                ('city', models.CharField(blank=True, default='nill', max_length=255)),
                ('state', models.CharField(blank=True, default='nill', max_length=255)),
                ('zip_code', models.CharField(blank=True, default='nill', max_length=255)),
                ('country', models.CharField(blank=True, default='nill', max_length=255)),
                ('shipping_address', models.TextField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_status', models.CharField(choices=[('PENDING', 'Pending'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction_reference', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('tracking_id', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('shipping_provider', models.CharField(blank=True, max_length=255, null=True)),
                ('shipping_token', models.CharField(blank=True, max_length=255, null=True)),
                ('shipping_terms', models.TextField(blank=True, null=True)),
                ('shipping_provider_image', models.URLField(blank=True, null=True)),
                ('shipping_currency', models.CharField(blank=True, max_length=10, null=True)),
                ('shipping_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=2)),
                ('color', models.CharField(choices=[('RED', 'Red'), ('BLUE', 'Blue'), ('GREEN', 'Green'), ('BLACK', 'Black'), ('WHITE', 'White'), ('LIGHT BLUE', 'Light blue'), ('DARK BLUE', 'Dark blue'), ('BROWN', 'Brown')], max_length=10)),
                ('stock', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='main.product')),
            ],
        ),
    ]
