# Generated by Django 5.0.8 on 2024-09-03 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('main', '0001_initial'), ('main', '0002_cart_rename_title_product_name_product_color_and_more'), ('main', '0003_remove_product_color_remove_product_size_and_more'), ('main', '0004_product_alternate_image'), ('main', '0005_alter_product_alternate_image_alter_product_image'), ('main', '0006_remove_order_product_remove_order_quantity'), ('main', '0007_order_tracking_id'), ('main', '0008_product_category'), ('main', '0009_alter_order_user'), ('main', '0010_alter_productvariant_color'), ('main', '0011_alter_product_category'), ('main', '0012_alter_product_category'), ('main', '0013_alter_productvariant_color'), ('main', '0014_order_city_order_country_order_email_and_more'), ('main', '0015_remove_cartitem_cart_remove_cartitem_product_and_more'), ('main', '0016_order_shipping_amount_order_shipping_amount_local_and_more'), ('main', '0017_delete_shippinginfo'), ('main', '0018_remove_order_shipping_estimated_days'), ('main', '0019_remove_order_shipping_service_name'), ('main', '0020_remove_order_shipping_amount_local')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='product_images/')),
                ('description', models.TextField(default='null')),
                ('alternate_image', models.ImageField(upload_to='product_images/')),
                ('category', models.CharField(choices=[('DRESS', 'Dress'), ('BAGS', 'Bags'), ('T-Shirts', 'T-Shirts'), ('SHIRTS', 'Shirts'), ('SKIRTS', 'Skirts')], default='DRESS', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shipping_address', models.TextField()),
                ('order_status', models.CharField(choices=[('PENDING', 'Pending'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tracking_id', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, default='nill', max_length=255)),
                ('country', models.CharField(blank=True, default='nill', max_length=255)),
                ('email', models.EmailField(default='nill', max_length=254)),
                ('first_name', models.TextField(blank=True, default='nill', max_length=255)),
                ('last_name', models.TextField(blank=True, default='nill', max_length=255)),
                ('state', models.CharField(blank=True, default='nill', max_length=255)),
                ('street', models.CharField(blank=True, default='nill', max_length=255)),
                ('zip_code', models.CharField(blank=True, default='nill', max_length=255)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('transaction_reference', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('shipping_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('shipping_currency', models.CharField(blank=True, max_length=10, null=True)),
                ('shipping_provider', models.CharField(blank=True, max_length=255, null=True)),
                ('shipping_provider_image', models.URLField(blank=True, null=True)),
                ('shipping_terms', models.TextField(blank=True, null=True)),
                ('shipping_token', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=2)),
                ('color', models.CharField(choices=[('RED', 'Red'), ('BLUE', 'Blue'), ('GREEN', 'Green'), ('BLACK', 'Black'), ('WHITE', 'White'), ('LIGHT BLUE', 'Light blue'), ('DARK BLUE', 'Dark blue'), ('BROWN', 'Brown')], max_length=10)),
                ('stock', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='main.product')),
            ],
        ),
    ]
