# Generated by Django 5.1 on 2024-08-18 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_product_color_remove_product_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='alternate_image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
