# Generated by Django 5.1 on 2024-08-18 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_product_alternate_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='alternate_image',
            field=models.ImageField(upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='product_images/'),
        ),
    ]
