# Generated by Django 5.1 on 2024-08-25 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_order_tracking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('DRESS', 'Dress'), ('BAGS', 'Bags')], default='DRESS', max_length=50),
        ),
    ]
