# Generated by Django 5.0.8 on 2024-08-27 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_productvariant_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('DRESS', 'Dress'), ('BAGS', 'Bags'), ('T-Shirts', 'T-Shirts'), ('SHIRTS', 'Shirts'), ('SKIRTS', 'SKIRTS')], default='DRESS', max_length=50),
        ),
    ]
