# Generated by Django 5.0.8 on 2024-08-29 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='color',
            field=models.CharField(choices=[('RED', 'Red'), ('BLUE', 'Blue'), ('GREEN', 'Green'), ('BLACK', 'Black'), ('WHITE', 'White'), ('LIGHT BLUE', 'Light blue'), ('DARK BLUE', 'Dark blue'), ('BROWN', 'Brown')], max_length=10),
        ),
    ]
