# Generated by Django 5.0.8 on 2024-09-02 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_productvariant_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, default='nill', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.CharField(blank=True, default='nill', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default='nill', max_length=254),
        ),
        migrations.AddField(
            model_name='order',
            name='first_name',
            field=models.TextField(blank=True, default='nill', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='last_name',
            field=models.TextField(blank=True, default='nill', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(blank=True, default='nill', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='street',
            field=models.CharField(blank=True, default='nill', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='zip_code',
            field=models.CharField(blank=True, default='nill', max_length=255),
        ),
    ]
